# Application Name
spring.application.name=transaction-service

# MongoDB Configuration
# spring.data.mongodb.uri=mongodb+srv://akentech:Bundes9898@cluster1.ftk04.mongodb.net/transaction-service?retryWrites=true&w=majority&appName=Cluster1
# spring.data.mongodb.database=transaction-service

# R2DBC Database Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5050/transaction-service
spring.r2dbc.username=akentech
spring.r2dbc.password=Bundes9898

logging.level.io.r2dbc=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG


# SQL Initialization
spring.sql.init.mode=always

# Disable Liquibase
spring.liquibase.enabled=false

# JPA Settings (not needed for R2DBC, but keeping in case for reference)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Active Profile
spring.profiles.active=prod
# Server Configuration
server.port=8084

# Banner Configuration
spring.main.banner-mode=off

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.akentech.transaction=DEBUG
logging.level.org.mongodb=DEBUG

# Test containers
testcontainers.reuse.enable=false
testcontainers.checks.disable=true
testcontainers.verbose=true

# Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:19092
#spring.kafka.bootstrap-servers=localhost:29092 // for internal docker services
spring.kafka.consumer.group-id=transaction-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.max-poll-records=500
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Logging with Loki
management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=transaction-service

management.tracing.sampling.probability=1.0