# Application Name
spring.application.name=expense-service

# MongoDB Configuration
# spring.data.mongodb.uri=mongodb+srv://akentech:Bundes9898@cluster1.ftk04.mongodb.net/expense-service?retryWrites=true&w=majority&appName=Cluster1
# spring.data.mongodb.database=expense-service

# PostgreSQL (R2DBC) Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5050/expense-service
spring.r2dbc.username=akentech
spring.r2dbc.password=Bundes9898

logging.level.io.r2dbc=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG


# Database Initialization
spring.sql.init.mode=always
spring.liquibase.enabled=false

# Hibernate (No Longer Needed with R2DBC)
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8082

# Banner Configuration
spring.main.banner-mode=off

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.akentech.expense=DEBUG
logging.level.org.postgresql=DEBUG

# Test containers
testcontainers.reuse.enable=false
testcontainers.checks.disable=true
testcontainers.verbose=true

# Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:19092
spring.kafka.consumer.group-id=expense-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Logging with Loki
management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=expense-service

management.tracing.sampling.probability=1.0