services:
  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-service
    restart: unless-stopped
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://akentech:Bundes9898@cluster1.ftk04.mongodb.net/transaction-service?retryWrites=true&w=majority&appName=Cluster1
      SPRING_PROFILES_ACTIVE: prod
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
    ports:
      - "9084:8084"
    networks:
      - kbf

networks:
  kbf:
    external: true