services:
  income-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: income-service
    restart: unless-stopped
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://akentech:Bundes9898@cluster1.ftk04.mongodb.net/income-service?retryWrites=true&w=majority&appName=Cluster1
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "9081:8081"
    networks:
      - kbf

networks:
  kbf:
    external: true