services:
  income-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: income-service
    restart: unless-stopped
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5050/income-service
      SPRING_R2DBC_USERNAME: akentech
      SPRING_R2DBC_PASSWORD: Bundes9898
      SPRING_PROFILES_ACTIVE: prod
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
    ports:
      - "9081:8081"
    networks:
      - kbf

networks:
  kbf:
    external: true
