services:
  investment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investment-service
    restart: unless-stopped
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5050/investment-service
      SPRING_R2DBC_USERNAME: akentech
      SPRING_R2DBC_PASSWORD: Bundes9898
      SPRING_PROFILES_ACTIVE: prod
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
    ports:
      - "9083:8083"
    networks:
      - kbf

networks:
  kbf:
    external: true
